# Generated by Django 4.2.2 on 2024-03-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_customuser_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
