# Generated by Django 4.2.2 on 2024-03-31 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_blockedip_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blockedip",
            old_name="ip_address",
            new_name="blocked_ip_address",
        ),
    ]
